import type { Locale } from './site-content';

export const legalPages = ['support', 'privacy', 'terms', 'copyright', 'sources'] as const;
export type LegalPage = (typeof legalPages)[number];
type LegalText = [summary: string, ...paragraphs: string[]];

// The canonical Russian and English legal pages remain at their established URLs.
// These localized pages carry the same material public boundaries in the app's languages.
export const legalContent: Record<Locale, Record<LegalPage, LegalText>> = {
  ru: {
    support: ['Помощь по приложению и удаление аккаунта закрытого пилота.', 'Напишите на support@partitoria.app. Укажите модель устройства, версию Android и Partitoria, последовательность действий и текст ошибки.', 'Не отправляйте ноты, резервные копии, пароли, коды или платёжные данные без отдельной договорённости о необходимости и безопасной передаче.', 'Приглашённый участник может запросить удаление аккаунта в приложении или по почте. Оператор отправит новый код на подтверждённый адрес; знания адреса недостаточно. Локальные ноты останутся на устройстве.'],
    privacy: ['Личная библиотека остаётся на устройстве; необязательный аккаунт доступен только приглашённым участникам.', 'PDF, аудио, записи, метаданные, теги, коллекции, история, пометки и программы хранятся локально и не отправляются на сервер Partitoria. Для библиотеки не нужен аккаунт; рекламы, поведенческой аналитики и социальных SDK нет.', 'Закрытый пилот обрабатывает подтверждённый email, ID аккаунта, открытый ключ установки, доказательство приложения/устройства, IP-запроса и состояние лицензии. Сервер выдаёт подписанный ограниченный офлайн-доступ, но не получает ноты. Публичной регистрации, покупок и подписок пока нет.', 'Коды отправляет Resend. Наш журнал метаданных доставки хранится до 90 дней, зашифрованные серверные копии — до 30 дней. Resend заявляет о хранении писем и журналов в США 30 дней; отслеживание открытий и переходов выключено.', 'Микрофон включается только после явного нажатия записи. Запись видна и прекращается при прерывании; она не анализируется и не загружается. Интернет-поиск по команде отправляет запросы внешним архивам по HTTPS; они получают обычные данные запроса, включая IP. Выбранное облачное хранилище обрабатывает ваши файлы по своим правилам.', 'Локальные элементы можно удалять и экспортировать. Аккаунт пилота удаляется после нового кода, в том числе по запросу без приложения; псевдонимизированный аудит хранится до 90 дней, зашифрованные копии — до 30 дней. Локальные ноты не удаляются, прежний офлайн-доступ может действовать до своего срока, не более 30 дней.', 'Приложение рассчитано на музыкантов от 13 лет и взрослых; для подростковых интернет-сервисов соблюдайте местные правила согласия. Автоматическая копия Android исключает базу библиотеки и управляемые файлы: для переноса используйте ручной экспорт.'],
    terms: ['Условия использования сайта и публично распространяемых версий Partitoria.', 'Partitoria помогает организовать и читать личную нотную библиотеку. Пользователь отвечает за законность получения, хранения, копирования, исполнения и распространения своих файлов.', 'Внешние архивы сами определяют содержание, лицензии, региональные ограничения и доступность. Сохраняйте проверенные резервные копии и не удаляйте единственный внешний оригинал после импорта.', 'Существенные изменения условий появятся здесь с новой датой. Вопросы: support@partitoria.app.'],
    copyright: ['Partitoria не передаёт прав на импортированные или найденные издания.', 'Используйте только файлы, на которые у вас есть права. Импорт, резервная копия и экспорт не меняют правовой статус издания.', 'Поиск в интернете отделён от личной библиотеки. Право загрузки проверяется для конкретного издания и региона; ссылка, атрибуция и лицензия сохраняются. Partitoria не продаёт чужие ноты как свои.', 'О спорной ссылке или описании сообщите на support@partitoria.app: укажите издание, точный URL, основание ваших прав, желаемое действие и контакт. Материал независимого сайта удаляет его оператор.'],
    sources: ['Поиск внешних изданий остаётся отдельным от личной библиотеки.', 'Он запускается только после явной команды. Прямая загрузка допускается только для общественного достояния или открытой лицензии, когда конкретный источник и издание разрешают это.', 'Иначе приложение открывает официальный сайт источника или сохраняет ссылку. Перед использованием проверяйте актуальную лицензию и региональные ограничения каждого издания.'],
  },
  en: {
    support: ['Help with the app and invited pilot account deletion.', 'Email support@partitoria.app with your device model, Android and Partitoria versions, the steps you took and any error text.', 'Do not send scores, backups, passwords, one-time codes or payment details unless a safe, necessary transfer has been agreed.', 'Invited users can request account deletion in the app or by email. The operator sends a fresh code to the confirmed address; knowing the address alone is insufficient. Local scores stay on the device.'],
    privacy: ['Your personal library stays on your device; an optional account is available only to invited pilot users.', 'PDFs, audio, recordings, metadata, tags, collections, history, marks and programmes remain local and are not sent to Partitoria servers. The library needs no account and contains no advertising, behavioural analytics or social SDKs.', 'The closed pilot processes confirmed email, account ID, installation public key, app/device proof, request IP and licence state. The server issues signed, time-limited offline access but receives no scores. Public registration, purchases and subscriptions are unavailable.', 'Resend delivers codes. Our code-free delivery metadata lasts up to 90 days and encrypted server backups up to 30 days. Resend states that message content and logs are kept in the US for 30 days. Open and click tracking are off.', 'The microphone is used only after you press Record. Recording stays visible and stops on interruption; it is not analysed or uploaded. Explicit online searches send queries over HTTPS to external archives, which receive ordinary request data including IP. A cloud document provider you select handles files under its own policy.', 'You may delete or export local items. A pilot account is deleted after a fresh code, including by request outside the app; pseudonymous audit data lasts up to 90 days and encrypted backups up to 30 days. Local scores remain, and an earlier offline grant may last until its expiry, at most 30 days.', 'Partitoria is for musicians aged 13 and over and adults; observe local consent rules for teenage online use. Android automatic backup excludes the library database and managed files: use manual export for transfer.'],
    terms: ['Terms for this website and publicly distributed Partitoria versions.', 'Partitoria organises and reads a personal sheet-music library. You are responsible for lawful acquisition, storage, copying, performance and distribution of your files.', 'Independent archives control their content, licences, regional restrictions and availability. Keep verified backups and do not delete your only external original after import.', 'Material changes will appear here with a new effective date. Questions: support@partitoria.app.'],
    copyright: ['Partitoria does not grant rights to imported or discovered editions.', 'Use only files you are entitled to use. Import, backup and export do not change an edition’s legal status.', 'Online discovery is separate from the personal library. Download eligibility depends on the edition and region; source links, attribution and licence are retained. Partitoria does not sell third-party scores as its own.', 'Report an infringing link or description to support@partitoria.app with the edition, exact URL, basis of your rights, requested action and contact. Only an independent site operator can remove material hosted there.'],
    sources: ['Discovery of external editions remains separate from your personal library.', 'A search starts only after your explicit action. Direct download is available only for public-domain or openly licensed editions when that source and edition permit it.', 'Otherwise the app opens the official source page or saves a reference. Check the current licence and regional restrictions for each edition.'],
  },
  de: {
    support: ['Hilfe zur App und Löschung eines eingeladenen Testkontos.', 'Schreiben Sie an support@partitoria.app mit Gerätemodell, Android- und Partitoria-Version, Schritten und Fehlermeldung.', 'Senden Sie keine Noten, Sicherungen, Passwörter, Einmalcodes oder Zahlungsdaten ohne eine gesondert vereinbarte sichere Übertragung.', 'Eingeladene können die Kontolöschung in der App oder per E-Mail beantragen. Der Betreiber sendet einen neuen Code an die bestätigte Adresse; die Adresse allein genügt nicht. Lokale Noten bleiben erhalten.'],
    privacy: ['Ihre Bibliothek bleibt auf dem Gerät; ein optionales Konto gibt es nur für eingeladene Tester.', 'PDFs, Audio, Aufnahmen, Metadaten, Tags, Sammlungen, Verlauf, Markierungen und Programme bleiben lokal. Sie werden nicht an Partitoria-Server gesendet. Die Bibliothek braucht kein Konto; Werbung, Verhaltensanalyse und soziale SDKs fehlen.', 'Der geschlossene Test verarbeitet bestätigte E-Mail, Konto-ID, öffentlichen Installationsschlüssel, App-/Gerätenachweis, Anfrage-IP und Lizenzstatus. Der Server stellt signierten, befristeten Offline-Zugang aus, erhält aber keine Noten. Öffentliche Registrierung, Kauf und Abo gibt es nicht.', 'Resend versendet Codes. Unser inhaltsfreies Zustellprotokoll bleibt bis zu 90 Tage, verschlüsselte Serversicherungen bis zu 30 Tage. Laut Resend bleiben Nachrichten und Protokolle 30 Tage in den USA. Öffnungs- und Klicktracking sind aus.', 'Das Mikrofon wird erst nach Druck auf Aufnahme genutzt. Die sichtbare Aufnahme stoppt bei Unterbrechung und wird weder analysiert noch hochgeladen. Ausdrückliche Online-Suchen senden Anfragen per HTTPS an externe Archive, die übliche Anfragedaten einschließlich IP erhalten. Ein gewählter Cloud-Dateianbieter verarbeitet Daten nach eigenen Regeln.', 'Lokale Elemente können gelöscht und exportiert werden. Ein Testkonto wird nach neuem Code auch ohne App gelöscht; pseudonyme Auditdaten bleiben bis zu 90 Tage, verschlüsselte Sicherungen bis zu 30 Tage. Lokale Noten bleiben; früherer Offline-Zugang kann bis zum Ablauf, höchstens 30 Tage, weitergelten.', 'Partitoria richtet sich an Musiker ab 13 Jahren und Erwachsene; beachten Sie lokale Einwilligungsregeln für Online-Dienste Minderjähriger. Die automatische Android-Sicherung schließt Bibliotheksdatenbank und verwaltete Dateien aus; nutzen Sie den manuellen Export.'],
    terms: ['Bedingungen für diese Website und öffentlich vertriebene Partitoria-Versionen.', 'Partitoria ordnet und liest eine persönliche Notenbibliothek. Sie sind für den rechtmäßigen Erwerb, die Speicherung, Kopie, Aufführung und Weitergabe Ihrer Dateien verantwortlich.', 'Unabhängige Archive bestimmen Inhalt, Lizenz, regionale Grenzen und Verfügbarkeit selbst. Bewahren Sie geprüfte Sicherungen auf und löschen Sie nach dem Import nicht Ihr einziges externes Original.', 'Wesentliche Änderungen erscheinen hier mit neuem Datum. Fragen: support@partitoria.app.'],
    copyright: ['Partitoria überträgt keine Rechte an importierten oder gefundenen Ausgaben.', 'Nutzen Sie nur berechtigt verwendbare Dateien. Import, Sicherung und Export ändern den Rechtsstatus nicht.', 'Online-Suche und Bibliothek sind getrennt. Der Download hängt von Ausgabe und Region ab; Quelle, Attribution und Lizenz bleiben erhalten. Partitoria verkauft fremde Noten nicht als eigene.', 'Melden Sie eine rechtsverletzende Verlinkung an support@partitoria.app mit Ausgabe, genauer URL, Rechtsgrundlage, gewünschter Maßnahme und Kontakt. Dateien unabhängiger Seiten kann nur deren Betreiber entfernen.'],
    sources: ['Externe Ausgaben werden getrennt von Ihrer Bibliothek gesucht.', 'Die Suche startet nur ausdrücklich. Direkter Download gilt nur für gemeinfreie oder offen lizenzierte Ausgaben, wenn Quelle und Ausgabe ihn erlauben.', 'Sonst öffnet die App die Quellseite oder speichert einen Verweis. Prüfen Sie aktuelle Lizenz und regionale Regeln je Ausgabe.'],
  },
  it: {
    support: ['Assistenza e cancellazione dell’account del test chiuso.', 'Scrivi a support@partitoria.app indicando dispositivo, versioni Android e Partitoria, passaggi ed eventuale errore.', 'Non inviare spartiti, backup, password, codici monouso o dati di pagamento senza un accordo su una trasmissione sicura e necessaria.', 'Gli invitati possono chiedere la cancellazione nell’app o via email. L’operatore invia un codice nuovo all’indirizzo confermato; conoscere l’indirizzo non basta. Gli spartiti locali restano.'],
    privacy: ['La biblioteca personale resta sul dispositivo; l’account facoltativo è solo per invitati al test.', 'PDF, audio, registrazioni, metadati, tag, raccolte, cronologia, annotazioni e programmi restano locali e non sono inviati ai server Partitoria. La biblioteca non richiede account, pubblicità, analisi comportamentale o SDK social.', 'Il test chiuso tratta email confermata, ID account, chiave pubblica dell’installazione, prova app/dispositivo, IP della richiesta e stato della licenza. Il server rilascia accesso offline firmato e limitato, senza ricevere spartiti. Non ci sono registrazione pubblica, acquisti o abbonamenti.', 'Resend invia i codici. I nostri metadati di consegna senza codice restano fino a 90 giorni, i backup cifrati del server fino a 30. Resend dichiara 30 giorni negli USA per messaggi e log. Tracciamento aperture e clic disattivato.', 'Il microfono si usa solo dopo aver premuto Registra. La registrazione è visibile, si ferma se interrotta, non viene analizzata né caricata. Le ricerche online esplicite inviano richieste HTTPS ad archivi esterni, che ricevono normali dati inclusi IP. Un provider cloud scelto da te tratta i file secondo le proprie regole.', 'Puoi eliminare o esportare dati locali. L’account del test viene cancellato dopo un nuovo codice, anche senza app; audit pseudonimo fino a 90 giorni e backup cifrati fino a 30. Gli spartiti locali restano; un accesso offline già concesso può durare fino alla scadenza, massimo 30 giorni.', 'Partitoria è per musicisti dai 13 anni e adulti; osserva le regole locali di consenso per servizi online dei minori. Il backup automatico Android esclude database e file gestiti: usa l’esportazione manuale.'],
    terms: ['Condizioni del sito e delle versioni pubbliche di Partitoria.', 'Partitoria organizza e legge una biblioteca personale di spartiti. Sei responsabile della legalità di acquisizione, conservazione, copia, esecuzione e distribuzione dei tuoi file.', 'Gli archivi indipendenti controllano contenuti, licenze, limiti regionali e disponibilità. Conserva backup verificati e non eliminare l’unico originale esterno dopo l’importazione.', 'Le modifiche sostanziali saranno pubblicate qui con nuova data. Domande: support@partitoria.app.'],
    copyright: ['Partitoria non concede diritti sulle edizioni importate o trovate.', 'Usa solo file che hai diritto di usare. Importazione, backup ed esportazione non ne cambiano lo stato giuridico.', 'La ricerca online è separata dalla biblioteca. Il download dipende da edizione e regione; fonte, attribuzione e licenza vengono conservate. Partitoria non vende spartiti altrui come propri.', 'Segnala un collegamento o descrizione lesiva a support@partitoria.app con edizione, URL esatto, base dei diritti, richiesta e recapito. I file ospitati altrove sono rimossi dall’operatore del sito.'],
    sources: ['Le edizioni esterne si cercano separatamente dalla biblioteca personale.', 'La ricerca parte solo su comando esplicito. Il download diretto vale per opere di pubblico dominio o licenze aperte quando fonte ed edizione lo permettono.', 'Altrimenti l’app apre la fonte ufficiale o salva un riferimento. Verifica licenza attuale e restrizioni regionali di ogni edizione.'],
  },
  es: {
    support: ['Ayuda y eliminación de la cuenta de la prueba cerrada.', 'Escribe a support@partitoria.app con el modelo, las versiones de Android y Partitoria, los pasos y el texto del error.', 'No envíes partituras, copias, contraseñas, códigos ni datos de pago sin acordar una transferencia segura y necesaria.', 'Los invitados pueden pedir la eliminación en la app o por correo. El operador envía un código nuevo a la dirección confirmada; conocer la dirección no basta. Las partituras locales permanecen.'],
    privacy: ['La biblioteca personal queda en el dispositivo; la cuenta opcional es solo para invitados.', 'PDF, audio, grabaciones, metadatos, etiquetas, colecciones, historial, anotaciones y programas permanecen locales y no se envían a los servidores Partitoria. La biblioteca no requiere cuenta y no incluye publicidad, análisis de conducta ni SDK sociales.', 'La prueba cerrada trata correo confirmado, ID de cuenta, clave pública de instalación, prueba de app/dispositivo, IP de la solicitud y estado de licencia. El servidor emite acceso sin conexión firmado y limitado; no recibe partituras. No hay registro, compras ni suscripciones públicas.', 'Resend entrega los códigos. Nuestros metadatos de entrega sin código duran hasta 90 días y las copias cifradas del servidor hasta 30. Resend declara 30 días en EE. UU. para mensajes y registros. El seguimiento de aperturas y clics está desactivado.', 'El micrófono se usa solo al pulsar Grabar. La grabación es visible, se detiene ante interrupciones y no se analiza ni sube. Una búsqueda explícita envía consultas HTTPS a archivos externos, que reciben datos habituales como la IP. Un proveedor de archivos en la nube que elijas trata tus datos con su política.', 'Puedes borrar o exportar datos locales. La cuenta de prueba se elimina tras un código nuevo, también sin la app; auditoría seudónima hasta 90 días y copias cifradas hasta 30. Las partituras locales quedan; un acceso previo sin conexión puede seguir hasta su vencimiento, máximo 30 días.', 'Partitoria es para músicos desde los 13 años y adultos; respeta las reglas locales de consentimiento para servicios en línea de menores. La copia automática de Android excluye la base y los archivos gestionados: usa la exportación manual.'],
    terms: ['Condiciones para este sitio y las versiones públicas de Partitoria.', 'Partitoria organiza y lee una biblioteca personal. Eres responsable de adquirir, guardar, copiar, interpretar y distribuir tus archivos legalmente.', 'Los archivos independientes controlan contenido, licencias, límites regionales y disponibilidad. Conserva copias verificadas y no borres tu único original externo tras importar.', 'Los cambios importantes se publicarán aquí con nueva fecha. Consultas: support@partitoria.app.'],
    copyright: ['Partitoria no concede derechos sobre ediciones importadas o encontradas.', 'Usa solo archivos que tengas derecho a utilizar. Importar, respaldar y exportar no cambia su situación jurídica.', 'La búsqueda en línea está separada de la biblioteca. La descarga depende de la edición y región; se conservan fuente, atribución y licencia. Partitoria no vende partituras ajenas como propias.', 'Comunica un enlace o descripción infractora a support@partitoria.app con edición, URL exacta, fundamento de tus derechos, acción solicitada y contacto. Solo el operador externo puede retirar archivos de su sitio.'],
    sources: ['Las ediciones externas se buscan aparte de la biblioteca personal.', 'La búsqueda solo empieza por orden expresa. La descarga directa se ofrece para dominio público o licencia abierta cuando fuente y edición lo permitan.', 'En otros casos la app abre la fuente oficial o guarda una referencia. Comprueba licencia y restricciones regionales de cada edición.'],
  },
  pt: {
    support: ['Apoio e eliminação da conta do teste fechado.', 'Escreva para support@partitoria.app com modelo, versões Android e Partitoria, passos e texto do erro.', 'Não envie partituras, cópias, palavras-passe, códigos ou dados de pagamento sem acordo sobre um envio seguro e necessário.', 'Convidados podem pedir eliminação na aplicação ou por email. O operador envia um novo código ao endereço confirmado; saber o endereço não basta. As partituras locais permanecem.'],
    privacy: ['A biblioteca pessoal fica no dispositivo; a conta opcional é só para convidados.', 'PDFs, áudio, gravações, metadados, etiquetas, coleções, histórico, anotações e programas ficam locais e não vão para servidores Partitoria. A biblioteca não precisa de conta nem inclui publicidade, análise comportamental ou SDK sociais.', 'O teste fechado trata email confirmado, ID de conta, chave pública de instalação, prova da app/dispositivo, IP do pedido e estado da licença. O servidor emite acesso offline assinado e limitado; não recebe partituras. Não há registo, compras ou subscrições públicas.', 'A Resend envia códigos. Metadados de entrega sem código duram até 90 dias e cópias cifradas do servidor até 30. A Resend declara 30 dias nos EUA para mensagens e registos. O seguimento de aberturas e cliques está desligado.', 'O microfone só é usado após premir Gravar. A gravação fica visível, para se for interrompida e não é analisada nem enviada. Pesquisa online explícita envia pedidos HTTPS a arquivos externos, que recebem dados normais como IP. Um fornecedor cloud escolhido por si trata os ficheiros pela própria política.', 'Pode apagar ou exportar dados locais. A conta do teste é apagada após novo código, mesmo sem a app; auditoria pseudónima até 90 dias e cópias cifradas até 30. As partituras locais ficam; acesso offline anterior pode durar até expirar, no máximo 30 dias.', 'Partitoria destina-se a músicos a partir dos 13 anos e adultos; cumpra regras locais de consentimento para serviços online de menores. A cópia automática Android exclui base e ficheiros geridos: use exportação manual.'],
    terms: ['Termos deste sítio e das versões públicas da Partitoria.', 'A Partitoria organiza e lê uma biblioteca pessoal. É responsável pela obtenção, guarda, cópia, execução e distribuição legais dos seus ficheiros.', 'Arquivos independentes controlam conteúdo, licenças, restrições regionais e disponibilidade. Guarde cópias verificadas e não apague o único original externo após importar.', 'Alterações importantes serão publicadas aqui com nova data. Questões: support@partitoria.app.'],
    copyright: ['A Partitoria não concede direitos sobre edições importadas ou encontradas.', 'Use só ficheiros a que tem direito. Importação, cópia e exportação não mudam o estado jurídico.', 'Pesquisa online e biblioteca são separadas. A transferência depende da edição e região; fonte, atribuição e licença são preservadas. A Partitoria não vende partituras de terceiros como próprias.', 'Comunique uma ligação ou descrição infratora a support@partitoria.app com edição, URL exato, fundamento dos direitos, ação desejada e contacto. Só o operador de um sítio externo pode remover os seus ficheiros.'],
    sources: ['A descoberta de edições externas é separada da biblioteca pessoal.', 'A pesquisa só começa por ação explícita. A transferência direta exige domínio público ou licença aberta e permissão da fonte e edição.', 'Caso contrário a aplicação abre a fonte oficial ou guarda uma referência. Confirme licença e restrições regionais de cada edição.'],
  },
  uk: {
    support: ['Допомога із застосунком і видаленням акаунта закритого тесту.', 'Напишіть на support@partitoria.app модель пристрою, версії Android і Partitoria, послідовність дій і текст помилки.', 'Не надсилайте ноти, копії, паролі, одноразові коди чи платіжні дані без окремої домовленості про безпечне передавання.', 'Запрошені учасники можуть запросити видалення у застосунку або листом. Оператор надішле новий код на підтверджену адресу; знання адреси недостатньо. Локальні ноти залишаться.'],
    privacy: ['Особиста бібліотека залишається на пристрої; необов’язковий акаунт доступний лише запрошеним.', 'PDF, аудіо, записи, метадані, теги, колекції, історія, помітки та програми зберігаються локально й не надсилаються на сервери Partitoria. Бібліотеці не потрібен акаунт; реклами, поведінкової аналітики та соціальних SDK немає.', 'Закритий тест обробляє підтверджений email, ID акаунта, відкритий ключ установки, доказ застосунку/пристрою, IP запиту та стан ліцензії. Сервер видає підписаний обмежений офлайн-доступ, але не отримує нот. Публічної реєстрації, покупок і підписок немає.', 'Коди доставляє Resend. Наш журнал метаданих без кодів зберігається до 90 днів, зашифровані серверні копії — до 30. За заявою Resend листи й журнали зберігаються в США 30 днів. Відстеження відкриттів і переходів вимкнене.', 'Мікрофон працює лише після натискання «Запис». Запис видимий, припиняється при перериванні, не аналізується й не завантажується. Явний пошук надсилає запити HTTPS зовнішнім архівам, які отримують звичайні дані, зокрема IP. Вибраний хмарний постачальник обробляє файли за власною політикою.', 'Локальні дані можна видаляти й експортувати. Акаунт тесту видаляється після нового коду, також без застосунку; псевдонімний аудит — до 90 днів, зашифровані копії — до 30. Локальні ноти залишаються, попередній офлайн-доступ може діяти до завершення, не більш як 30 днів.', 'Partitoria призначена музикантам від 13 років і дорослим; дотримуйтеся місцевих правил згоди для підліткових онлайн-сервісів. Автокопія Android виключає базу й керовані файли: для перенесення використовуйте ручний експорт.'],
    terms: ['Умови цього сайту й публічно розповсюджуваних версій Partitoria.', 'Partitoria впорядковує та показує особисту бібліотеку нот. Користувач відповідає за законність отримання, зберігання, копіювання, виконання й поширення файлів.', 'Незалежні архіви самі визначають вміст, ліцензії, регіональні обмеження й доступність. Зберігайте перевірені копії та не видаляйте єдиний зовнішній оригінал після імпорту.', 'Суттєві зміни будуть опубліковані тут із новою датою. Питання: support@partitoria.app.'],
    copyright: ['Partitoria не надає прав на імпортовані чи знайдені видання.', 'Користуйтеся лише файлами, на які маєте права. Імпорт, копія й експорт не змінюють правового статусу.', 'Інтернет-пошук відділений від бібліотеки. Завантаження залежить від видання й регіону; джерело, атрибуція та ліцензія зберігаються. Partitoria не продає чужі ноти як власні.', 'Про спірне посилання чи опис напишіть на support@partitoria.app: видання, точний URL, підстава прав, бажана дія та контакт. Файл на незалежному сайті може видалити лише його оператор.'],
    sources: ['Пошук зовнішніх видань відділений від особистої бібліотеки.', 'Він починається лише за явною командою. Пряме завантаження допускається для суспільного надбання чи відкритої ліцензії, якщо джерело й видання це дозволяють.', 'Інакше застосунок відкриває офіційне джерело або зберігає посилання. Перевіряйте чинну ліцензію та регіональні правила кожного видання.'],
  },
  fr: {
    support: ['Aide pour l’application et suppression d’un compte du test fermé.', 'Écrivez à support@partitoria.app avec le modèle, les versions Android et Partitoria, les étapes et le message d’erreur.', 'N’envoyez pas de partitions, sauvegardes, mots de passe, codes ni données de paiement sans accord sur un transfert sûr et nécessaire.', 'Les invités peuvent demander la suppression dans l’application ou par courriel. L’opérateur envoie un nouveau code à l’adresse confirmée ; connaître l’adresse ne suffit pas. Les partitions locales restent.'],
    privacy: ['Votre bibliothèque reste sur l’appareil ; le compte facultatif est réservé aux invités.', 'PDF, audio, enregistrements, métadonnées, étiquettes, collections, historique, annotations et programmes restent locaux et ne vont pas aux serveurs Partitoria. La bibliothèque ne requiert aucun compte, publicité, analyse comportementale ou SDK social.', 'Le test fermé traite courriel confirmé, ID de compte, clé publique d’installation, preuve application/appareil, IP de requête et état de licence. Le serveur émet un accès hors ligne signé et limité, sans recevoir de partitions. Inscription, achat et abonnement publics sont indisponibles.', 'Resend transmet les codes. Nos métadonnées de livraison sans code durent jusqu’à 90 jours, les sauvegardes chiffrées du serveur jusqu’à 30. Resend indique 30 jours aux États-Unis pour messages et journaux. Suivi des ouvertures et clics désactivé.', 'Le microphone sert seulement après avoir appuyé sur Enregistrer. L’enregistrement est visible, s’arrête si interrompu et n’est ni analysé ni transféré. Une recherche en ligne explicite envoie des requêtes HTTPS aux archives externes, qui reçoivent les données ordinaires dont l’IP. Un fournisseur cloud choisi traite vos fichiers selon sa politique.', 'Vous pouvez supprimer ou exporter les données locales. Le compte du test est supprimé après un nouveau code, même sans application ; audit pseudonyme jusqu’à 90 jours et sauvegardes chiffrées jusqu’à 30. Les partitions locales restent ; un accès hors ligne antérieur peut durer jusqu’à son échéance, au plus 30 jours.', 'Partitoria s’adresse aux musiciens de 13 ans et plus et aux adultes ; respectez les règles locales de consentement pour les services en ligne des mineurs. La sauvegarde automatique Android exclut base et fichiers gérés : utilisez l’export manuel.'],
    terms: ['Conditions du site et des versions publiques de Partitoria.', 'Partitoria organise et lit une bibliothèque personnelle. Vous êtes responsable de l’acquisition, du stockage, de la copie, de l’exécution et de la diffusion licites de vos fichiers.', 'Les archives indépendantes contrôlent contenu, licences, restrictions régionales et disponibilité. Gardez des sauvegardes vérifiées et ne supprimez pas votre seul original externe après import.', 'Les changements importants paraîtront ici avec une nouvelle date. Questions : support@partitoria.app.'],
    copyright: ['Partitoria ne cède aucun droit sur les éditions importées ou trouvées.', 'Utilisez seulement des fichiers que vous avez le droit d’utiliser. Import, sauvegarde et export ne modifient pas leur statut juridique.', 'La recherche en ligne est distincte de la bibliothèque. Le téléchargement dépend de l’édition et de la région ; source, attribution et licence sont conservées. Partitoria ne vend pas les partitions d’autrui comme les siennes.', 'Signalez un lien ou descriptif litigieux à support@partitoria.app avec édition, URL précise, fondement de vos droits, action souhaitée et contact. Seul l’exploitant d’un site indépendant peut en retirer ses fichiers.'],
    sources: ['La recherche d’éditions externes est séparée de votre bibliothèque.', 'Elle commence seulement sur action explicite. Le téléchargement direct exige le domaine public ou une licence ouverte et l’autorisation de la source et de l’édition.', 'Sinon l’application ouvre la source officielle ou garde un lien. Vérifiez licence en vigueur et restrictions régionales pour chaque édition.'],
  },
  pl: {
    support: ['Pomoc i usunięcie konta zamkniętych testów.', 'Napisz na support@partitoria.app, podając model, wersje Androida i Partitorii, kroki oraz treść błędu.', 'Nie wysyłaj nut, kopii, haseł, kodów ani danych płatności bez uzgodnienia bezpiecznej i potrzebnej metody.', 'Zaproszeni użytkownicy mogą wnioskować o usunięcie w aplikacji lub e-mailem. Operator wyśle nowy kod na potwierdzony adres; znajomość adresu nie wystarczy. Lokalne nuty pozostają.'],
    privacy: ['Osobista biblioteka zostaje na urządzeniu; opcjonalne konto jest tylko dla zaproszonych.', 'PDF, dźwięk, nagrania, metadane, tagi, kolekcje, historia, adnotacje i programy pozostają lokalnie i nie trafiają na serwery Partitorii. Biblioteka nie wymaga konta; nie ma reklam, analityki zachowania ani społecznościowych SDK.', 'Test zamknięty przetwarza potwierdzony e-mail, ID konta, publiczny klucz instalacji, dowód aplikacji/urządzenia, IP żądania i stan licencji. Serwer wydaje podpisany, ograniczony dostęp offline, lecz nie dostaje nut. Publiczna rejestracja, zakupy i subskrypcje są niedostępne.', 'Resend dostarcza kody. Nasze metadane doręczenia bez kodów trwają do 90 dni, zaszyfrowane kopie serwera do 30. Według Resend wiadomości i logi pozostają w USA 30 dni. Śledzenie otwarć i kliknięć jest wyłączone.', 'Mikrofon działa dopiero po naciśnięciu Nagrywaj. Nagranie jest widoczne, kończy się po przerwaniu i nie jest analizowane ani wysyłane. Jawne wyszukiwanie online wysyła żądania HTTPS do zewnętrznych archiwów, które dostają zwykłe dane, w tym IP. Wybrany dostawca chmury obsługuje pliki według swojej polityki.', 'Możesz usuwać lub eksportować dane lokalne. Konto testowe usuwa się po nowym kodzie, także bez aplikacji; pseudonimowy audyt do 90 dni, zaszyfrowane kopie do 30. Lokalne nuty zostają; wcześniejszy dostęp offline może trwać do terminu, najwyżej 30 dni.', 'Partitoria jest dla muzyków od 13 lat i dorosłych; przestrzegaj lokalnych zasad zgody na usługi online dla nieletnich. Automatyczna kopia Androida wyklucza bazę i pliki zarządzane: do przenoszenia użyj ręcznego eksportu.'],
    terms: ['Warunki witryny i publicznych wersji Partitorii.', 'Partitoria porządkuje i wyświetla osobistą bibliotekę nut. Odpowiadasz za legalne nabycie, przechowanie, kopiowanie, wykonywanie i udostępnianie plików.', 'Niezależne archiwa same kontrolują treści, licencje, ograniczenia regionalne i dostępność. Zachowaj zweryfikowane kopie i nie usuwaj jedynego zewnętrznego oryginału po imporcie.', 'Istotne zmiany pojawią się tutaj z nową datą. Pytania: support@partitoria.app.'],
    copyright: ['Partitoria nie nadaje praw do zaimportowanych ani znalezionych wydań.', 'Korzystaj tylko z plików, do których masz prawo. Import, kopia i eksport nie zmieniają statusu prawnego.', 'Wyszukiwanie online jest oddzielone od biblioteki. Pobieranie zależy od wydania i regionu; źródło, autorstwo i licencja są zachowane. Partitoria nie sprzedaje cudzych nut jako własnych.', 'Zgłoś sporny link lub opis na support@partitoria.app, podając wydanie, dokładny URL, podstawę praw, oczekiwane działanie i kontakt. Plik na niezależnej stronie usuwa jej operator.'],
    sources: ['Zewnętrzne wydania wyszukuje się oddzielnie od biblioteki osobistej.', 'Wyszukiwanie zaczyna się tylko na wyraźne polecenie. Bezpośrednie pobranie wymaga domeny publicznej lub otwartej licencji oraz zgody źródła i wydania.', 'W pozostałych przypadkach aplikacja otwiera oficjalne źródło lub zapisuje odnośnik. Sprawdź bieżącą licencję i zasady regionalne każdego wydania.'],
  },
};
