import type { Locale } from './site-content';
import privacyContract from './privacy-contract.json';

export const legalPages = ['support', 'privacy', 'terms', 'copyright', 'sources'] as const;
export type LegalPage = (typeof legalPages)[number];
type LegalText = [summary: string, ...paragraphs: string[]];

// The canonical Russian and English legal pages remain at their established URLs.
// These localized pages carry the same material public boundaries in the app's languages.
export const legalContent: Record<Locale, Record<LegalPage, LegalText>> = {
  ru: {
    support: ["Помощь по Partitoria, библиотеке и магазинной подписке.","Напишите на support@partitoria.app. Укажите модель устройства, версию Android и Partitoria, последовательность действий и текст ошибки.","Не отправляйте ноты, резервные копии, пароли, коды или платёжные данные без отдельной договорённости о необходимости и безопасной передаче.","Подписку отменяют в Google Play; удаление приложения её не отменяет. Для восстановления покупки используйте тот же Google-аккаунт. При проблеме напишите нам без токена покупки и платёжных секретов. Сохранённые файлы и результаты доступны для чтения, экспорта и восстановления после Pro."],
    privacy: privacyContract.ru as LegalText,
    terms: ['Условия использования сайта и публично распространяемых версий Partitoria.', 'Partitoria помогает организовать и читать личную нотную библиотеку. Пользователь отвечает за законность получения, хранения, копирования, исполнения и распространения своих файлов.', 'Внешние архивы сами определяют содержание, лицензии, региональные ограничения и доступность. Сохраняйте проверенные резервные копии и не удаляйте единственный внешний оригинал после импорта.', 'Существенные изменения условий появятся здесь с новой датой. Вопросы: support@partitoria.app.'],
    copyright: ['Partitoria не передаёт прав на импортированные или найденные издания.', 'Используйте только файлы, на которые у вас есть права. Импорт, резервная копия и экспорт не меняют правовой статус издания.', 'Поиск в интернете отделён от личной библиотеки. Право загрузки проверяется для конкретного издания и региона; ссылка, атрибуция и лицензия сохраняются. Partitoria не продаёт чужие ноты как свои.', 'О спорной ссылке или описании сообщите на support@partitoria.app: укажите издание, точный URL, основание ваших прав, желаемое действие и контакт. Материал независимого сайта удаляет его оператор.'],
    sources: ['Поиск внешних изданий остаётся отдельным от личной библиотеки.', 'Он запускается только после явной команды. Прямая загрузка допускается только для общественного достояния или открытой лицензии, когда конкретный источник и издание разрешают это.', 'Иначе приложение открывает официальный сайт источника или сохраняет ссылку. Перед использованием проверяйте актуальную лицензию и региональные ограничения каждого издания.'],
  },
  en: {
    support: ["Help with Partitoria, your library and store subscriptions.","Email support@partitoria.app with your device model, Android and Partitoria versions, the steps you took and any error text.","Do not send scores, backups, passwords, one-time codes or payment details unless a safe, necessary transfer has been agreed.","Cancel subscriptions in Google Play; uninstalling does not cancel them. Restore purchases with the same Google account. For a problem, contact us without purchase tokens or payment secrets. Saved files and results remain readable, exportable and recoverable after Pro."],
    privacy: privacyContract.en as LegalText,
    terms: ['Terms for this website and publicly distributed Partitoria versions.', 'Partitoria organises and reads a personal sheet-music library. You are responsible for lawful acquisition, storage, copying, performance and distribution of your files.', 'Independent archives control their content, licences, regional restrictions and availability. Keep verified backups and do not delete your only external original after import.', 'Material changes will appear here with a new effective date. Questions: support@partitoria.app.'],
    copyright: ['Partitoria does not grant rights to imported or discovered editions.', 'Use only files you are entitled to use. Import, backup and export do not change an edition’s legal status.', 'Online discovery is separate from the personal library. Download eligibility depends on the edition and region; source links, attribution and licence are retained. Partitoria does not sell third-party scores as its own.', 'Report an infringing link or description to support@partitoria.app with the edition, exact URL, basis of your rights, requested action and contact. Only an independent site operator can remove material hosted there.'],
    sources: ['Discovery of external editions remains separate from your personal library.', 'A search starts only after your explicit action. Direct download is available only for public-domain or openly licensed editions when that source and edition permit it.', 'Otherwise the app opens the official source page or saves a reference. Check the current licence and regional restrictions for each edition.'],
  },
  de: {
    support: ["Hilfe zu Partitoria, Ihrer Bibliothek und Store-Abonnements.","Schreiben Sie an support@partitoria.app mit Gerätemodell, Android- und Partitoria-Version, Schritten und Fehlermeldung.","Senden Sie keine Noten, Sicherungen, Passwörter, Einmalcodes oder Zahlungsdaten ohne eine gesondert vereinbarte sichere Übertragung.","Kündigen Sie Abonnements in Google Play; Deinstallation kündigt nicht. Stellen Sie Käufe mit demselben Google-Konto wieder her. Kontaktieren Sie uns bei Problemen ohne Kauftoken oder Zahlungsgeheimnisse. Gespeicherte Dateien bleiben nach Pro lesbar, exportierbar und wiederherstellbar."],
    privacy: privacyContract.de as LegalText,
    terms: ['Bedingungen für diese Website und öffentlich vertriebene Partitoria-Versionen.', 'Partitoria ordnet und liest eine persönliche Notenbibliothek. Sie sind für den rechtmäßigen Erwerb, die Speicherung, Kopie, Aufführung und Weitergabe Ihrer Dateien verantwortlich.', 'Unabhängige Archive bestimmen Inhalt, Lizenz, regionale Grenzen und Verfügbarkeit selbst. Bewahren Sie geprüfte Sicherungen auf und löschen Sie nach dem Import nicht Ihr einziges externes Original.', 'Wesentliche Änderungen erscheinen hier mit neuem Datum. Fragen: support@partitoria.app.'],
    copyright: ['Partitoria überträgt keine Rechte an importierten oder gefundenen Ausgaben.', 'Nutzen Sie nur berechtigt verwendbare Dateien. Import, Sicherung und Export ändern den Rechtsstatus nicht.', 'Online-Suche und Bibliothek sind getrennt. Der Download hängt von Ausgabe und Region ab; Quelle, Attribution und Lizenz bleiben erhalten. Partitoria verkauft fremde Noten nicht als eigene.', 'Melden Sie eine rechtsverletzende Verlinkung an support@partitoria.app mit Ausgabe, genauer URL, Rechtsgrundlage, gewünschter Maßnahme und Kontakt. Dateien unabhängiger Seiten kann nur deren Betreiber entfernen.'],
    sources: ['Externe Ausgaben werden getrennt von Ihrer Bibliothek gesucht.', 'Die Suche startet nur ausdrücklich. Direkter Download gilt nur für gemeinfreie oder offen lizenzierte Ausgaben, wenn Quelle und Ausgabe ihn erlauben.', 'Sonst öffnet die App die Quellseite oder speichert einen Verweis. Prüfen Sie aktuelle Lizenz und regionale Regeln je Ausgabe.'],
  },
  it: {
    support: ["Assistenza per Partitoria, biblioteca e abbonamenti dello store.","Scrivi a support@partitoria.app indicando dispositivo, versioni Android e Partitoria, passaggi ed eventuale errore.","Non inviare spartiti, backup, password, codici monouso o dati di pagamento senza un accordo su una trasmissione sicura e necessaria.","Disdici gli abbonamenti in Google Play; disinstallare non li annulla. Ripristina con lo stesso account Google. In caso di problemi contattaci senza token o segreti di pagamento. File e risultati salvati restano leggibili, esportabili e recuperabili dopo Pro."],
    privacy: privacyContract.it as LegalText,
    terms: ['Condizioni del sito e delle versioni pubbliche di Partitoria.', 'Partitoria organizza e legge una biblioteca personale di spartiti. Sei responsabile della legalità di acquisizione, conservazione, copia, esecuzione e distribuzione dei tuoi file.', 'Gli archivi indipendenti controllano contenuti, licenze, limiti regionali e disponibilità. Conserva backup verificati e non eliminare l’unico originale esterno dopo l’importazione.', 'Le modifiche sostanziali saranno pubblicate qui con nuova data. Domande: support@partitoria.app.'],
    copyright: ['Partitoria non concede diritti sulle edizioni importate o trovate.', 'Usa solo file che hai diritto di usare. Importazione, backup ed esportazione non ne cambiano lo stato giuridico.', 'La ricerca online è separata dalla biblioteca. Il download dipende da edizione e regione; fonte, attribuzione e licenza vengono conservate. Partitoria non vende spartiti altrui come propri.', 'Segnala un collegamento o descrizione lesiva a support@partitoria.app con edizione, URL esatto, base dei diritti, richiesta e recapito. I file ospitati altrove sono rimossi dall’operatore del sito.'],
    sources: ['Le edizioni esterne si cercano separatamente dalla biblioteca personale.', 'La ricerca parte solo su comando esplicito. Il download diretto vale per opere di pubblico dominio o licenze aperte quando fonte ed edizione lo permettono.', 'Altrimenti l’app apre la fonte ufficiale o salva un riferimento. Verifica licenza attuale e restrizioni regionali di ogni edizione.'],
  },
  es: {
    support: ["Ayuda con Partitoria, biblioteca y suscripciones de la tienda.","Escribe a support@partitoria.app con el modelo, las versiones de Android y Partitoria, los pasos y el texto del error.","No envíes partituras, copias, contraseñas, códigos ni datos de pago sin acordar una transferencia segura y necesaria.","Cancela suscripciones en Google Play; desinstalar no las cancela. Restaura con la misma cuenta de Google. Ante problemas, contáctanos sin tokens ni secretos de pago. Archivos y resultados guardados siguen legibles, exportables y recuperables tras Pro."],
    privacy: privacyContract.es as LegalText,
    terms: ['Condiciones para este sitio y las versiones públicas de Partitoria.', 'Partitoria organiza y lee una biblioteca personal. Eres responsable de adquirir, guardar, copiar, interpretar y distribuir tus archivos legalmente.', 'Los archivos independientes controlan contenido, licencias, límites regionales y disponibilidad. Conserva copias verificadas y no borres tu único original externo tras importar.', 'Los cambios importantes se publicarán aquí con nueva fecha. Consultas: support@partitoria.app.'],
    copyright: ['Partitoria no concede derechos sobre ediciones importadas o encontradas.', 'Usa solo archivos que tengas derecho a utilizar. Importar, respaldar y exportar no cambia su situación jurídica.', 'La búsqueda en línea está separada de la biblioteca. La descarga depende de la edición y región; se conservan fuente, atribución y licencia. Partitoria no vende partituras ajenas como propias.', 'Comunica un enlace o descripción infractora a support@partitoria.app con edición, URL exacta, fundamento de tus derechos, acción solicitada y contacto. Solo el operador externo puede retirar archivos de su sitio.'],
    sources: ['Las ediciones externas se buscan aparte de la biblioteca personal.', 'La búsqueda solo empieza por orden expresa. La descarga directa se ofrece para dominio público o licencia abierta cuando fuente y edición lo permitan.', 'En otros casos la app abre la fuente oficial o guarda una referencia. Comprueba licencia y restricciones regionales de cada edición.'],
  },
  pt: {
    support: ["Ajuda com Partitoria, biblioteca e subscrições da loja.","Escreva para support@partitoria.app com modelo, versões Android e Partitoria, passos e texto do erro.","Não envie partituras, cópias, palavras-passe, códigos ou dados de pagamento sem acordo sobre um envio seguro e necessário.","Cancele subscrições na Google Play; desinstalar não as cancela. Restaure com a mesma conta Google. Contacte-nos sem tokens ou segredos de pagamento. Ficheiros e resultados guardados continuam legíveis, exportáveis e recuperáveis depois de Pro."],
    privacy: privacyContract.pt as LegalText,
    terms: ['Termos deste sítio e das versões públicas da Partitoria.', 'A Partitoria organiza e lê uma biblioteca pessoal. É responsável pela obtenção, guarda, cópia, execução e distribuição legais dos seus ficheiros.', 'Arquivos independentes controlam conteúdo, licenças, restrições regionais e disponibilidade. Guarde cópias verificadas e não apague o único original externo após importar.', 'Alterações importantes serão publicadas aqui com nova data. Questões: support@partitoria.app.'],
    copyright: ['A Partitoria não concede direitos sobre edições importadas ou encontradas.', 'Use só ficheiros a que tem direito. Importação, cópia e exportação não mudam o estado jurídico.', 'Pesquisa online e biblioteca são separadas. A transferência depende da edição e região; fonte, atribuição e licença são preservadas. A Partitoria não vende partituras de terceiros como próprias.', 'Comunique uma ligação ou descrição infratora a support@partitoria.app com edição, URL exato, fundamento dos direitos, ação desejada e contacto. Só o operador de um sítio externo pode remover os seus ficheiros.'],
    sources: ['A descoberta de edições externas é separada da biblioteca pessoal.', 'A pesquisa só começa por ação explícita. A transferência direta exige domínio público ou licença aberta e permissão da fonte e edição.', 'Caso contrário a aplicação abre a fonte oficial ou guarda uma referência. Confirme licença e restrições regionais de cada edição.'],
  },
  uk: {
    support: ["Допомога з Partitoria, бібліотекою та магазинною підпискою.","Напишіть на support@partitoria.app модель пристрою, версії Android і Partitoria, послідовність дій і текст помилки.","Не надсилайте ноти, копії, паролі, одноразові коди чи платіжні дані без окремої домовленості про безпечне передавання.","Скасовуйте підписку в Google Play; видалення застосунку її не скасовує. Відновлюйте купівлю з тим самим Google-акаунтом. Звертайтеся без токенів чи платіжних секретів. Збережені файли й результати доступні для читання, експорту й відновлення після Pro."],
    privacy: privacyContract.uk as LegalText,
    terms: ['Умови цього сайту й публічно розповсюджуваних версій Partitoria.', 'Partitoria впорядковує та показує особисту бібліотеку нот. Користувач відповідає за законність отримання, зберігання, копіювання, виконання й поширення файлів.', 'Незалежні архіви самі визначають вміст, ліцензії, регіональні обмеження й доступність. Зберігайте перевірені копії та не видаляйте єдиний зовнішній оригінал після імпорту.', 'Суттєві зміни будуть опубліковані тут із новою датою. Питання: support@partitoria.app.'],
    copyright: ['Partitoria не надає прав на імпортовані чи знайдені видання.', 'Користуйтеся лише файлами, на які маєте права. Імпорт, копія й експорт не змінюють правового статусу.', 'Інтернет-пошук відділений від бібліотеки. Завантаження залежить від видання й регіону; джерело, атрибуція та ліцензія зберігаються. Partitoria не продає чужі ноти як власні.', 'Про спірне посилання чи опис напишіть на support@partitoria.app: видання, точний URL, підстава прав, бажана дія та контакт. Файл на незалежному сайті може видалити лише його оператор.'],
    sources: ['Пошук зовнішніх видань відділений від особистої бібліотеки.', 'Він починається лише за явною командою. Пряме завантаження допускається для суспільного надбання чи відкритої ліцензії, якщо джерело й видання це дозволяють.', 'Інакше застосунок відкриває офіційне джерело або зберігає посилання. Перевіряйте чинну ліцензію та регіональні правила кожного видання.'],
  },
  fr: {
    support: ["Aide pour Partitoria, votre bibliothèque et les abonnements.","Écrivez à support@partitoria.app avec le modèle, les versions Android et Partitoria, les étapes et le message d’erreur.","N’envoyez pas de partitions, sauvegardes, mots de passe, codes ni données de paiement sans accord sur un transfert sûr et nécessaire.","Résiliez les abonnements dans Google Play ; désinstaller ne les résilie pas. Restaurez avec le même compte Google. Contactez-nous sans jeton ni secret de paiement. Fichiers et résultats sauvegardés restent lisibles, exportables et récupérables après Pro."],
    privacy: privacyContract.fr as LegalText,
    terms: ['Conditions du site et des versions publiques de Partitoria.', 'Partitoria organise et lit une bibliothèque personnelle. Vous êtes responsable de l’acquisition, du stockage, de la copie, de l’exécution et de la diffusion licites de vos fichiers.', 'Les archives indépendantes contrôlent contenu, licences, restrictions régionales et disponibilité. Gardez des sauvegardes vérifiées et ne supprimez pas votre seul original externe après import.', 'Les changements importants paraîtront ici avec une nouvelle date. Questions : support@partitoria.app.'],
    copyright: ['Partitoria ne cède aucun droit sur les éditions importées ou trouvées.', 'Utilisez seulement des fichiers que vous avez le droit d’utiliser. Import, sauvegarde et export ne modifient pas leur statut juridique.', 'La recherche en ligne est distincte de la bibliothèque. Le téléchargement dépend de l’édition et de la région ; source, attribution et licence sont conservées. Partitoria ne vend pas les partitions d’autrui comme les siennes.', 'Signalez un lien ou descriptif litigieux à support@partitoria.app avec édition, URL précise, fondement de vos droits, action souhaitée et contact. Seul l’exploitant d’un site indépendant peut en retirer ses fichiers.'],
    sources: ['La recherche d’éditions externes est séparée de votre bibliothèque.', 'Elle commence seulement sur action explicite. Le téléchargement direct exige le domaine public ou une licence ouverte et l’autorisation de la source et de l’édition.', 'Sinon l’application ouvre la source officielle ou garde un lien. Vérifiez licence en vigueur et restrictions régionales pour chaque édition.'],
  },
  pl: {
    support: ["Pomoc z Partitoria, biblioteką i subskrypcjami sklepu.","Napisz na support@partitoria.app, podając model, wersje Androida i Partitorii, kroki oraz treść błędu.","Nie wysyłaj nut, kopii, haseł, kodów ani danych płatności bez uzgodnienia bezpiecznej i potrzebnej metody.","Anuluj subskrypcje w Google Play; odinstalowanie ich nie anuluje. Przywracaj z tym samym kontem Google. Napisz bez tokenów i sekretów płatniczych. Zapisane pliki i wyniki pozostają czytelne, eksportowalne i możliwe do odzyskania po Pro."],
    privacy: privacyContract.pl as LegalText,
    terms: ['Warunki witryny i publicznych wersji Partitorii.', 'Partitoria porządkuje i wyświetla osobistą bibliotekę nut. Odpowiadasz za legalne nabycie, przechowanie, kopiowanie, wykonywanie i udostępnianie plików.', 'Niezależne archiwa same kontrolują treści, licencje, ograniczenia regionalne i dostępność. Zachowaj zweryfikowane kopie i nie usuwaj jedynego zewnętrznego oryginału po imporcie.', 'Istotne zmiany pojawią się tutaj z nową datą. Pytania: support@partitoria.app.'],
    copyright: ['Partitoria nie nadaje praw do zaimportowanych ani znalezionych wydań.', 'Korzystaj tylko z plików, do których masz prawo. Import, kopia i eksport nie zmieniają statusu prawnego.', 'Wyszukiwanie online jest oddzielone od biblioteki. Pobieranie zależy od wydania i regionu; źródło, autorstwo i licencja są zachowane. Partitoria nie sprzedaje cudzych nut jako własnych.', 'Zgłoś sporny link lub opis na support@partitoria.app, podając wydanie, dokładny URL, podstawę praw, oczekiwane działanie i kontakt. Plik na niezależnej stronie usuwa jej operator.'],
    sources: ['Zewnętrzne wydania wyszukuje się oddzielnie od biblioteki osobistej.', 'Wyszukiwanie zaczyna się tylko na wyraźne polecenie. Bezpośrednie pobranie wymaga domeny publicznej lub otwartej licencji oraz zgody źródła i wydania.', 'W pozostałych przypadkach aplikacja otwiera oficjalne źródło lub zapisuje odnośnik. Sprawdź bieżącą licencję i zasady regionalne każdego wydania.'],
  },
};
